; tree generated by count-change procedure for 11 cents:

; (count-change 11)
; (cc 11 5)
; (+ (cc 11 4) (cc (- 11 (first-demonination 5))
;                     5))
; (+ (cc 11 4) (cc -39 5))
; (+ (cc 11 4) 0) etc...

; tree was drawn on paper

; what are the orders of growth of space and #steps by this process as the amount to be changed increases?

; tree depth is proportional to amount of change - so linear space O(n)
; we can use induction to show that the #steps goes with O(n^5) [proof to follow...]